name: Ejecutar script diariamente

on:
  workflow_dispatch:   # permite ejecutarlo manualmente
  schedule:
    - cron: "0 15 * * *"  # UTC: 15 = 9 AM CDMX

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configurar credenciales
        run: echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json


      - name: Ejecutar script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python expediente.py

